owner: lehuygiang28
repo: uptime-tracking

sites:
  - name: Giaang Homepage
    url: https://giaang.id.vn
  - name: Giaang Uptime page
    url: https://uptime.giaang.id.vn
  - name: vnpayjs Documentations
    url: https://vnpay.js.org
  - name: '@vn-utils/text Documentations'
    url: https://vn-text.vercel.app
  - name: TaskTr UI
    url: https://tasktr.vercel.app/api/ping
  - name: TaskTr API
    url: https://lehuygiang28-tasktr-api.hf.space/api/ping

assignees:
  - lehuygiang28
status-website:
  cname: uptime.giaang.id.vn
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "giaang's uptime page"
  introTitle: "giaang's project uptime status page"
  introMessage: This is a status page which uses **real-time** data for my projects
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/lehuygiang28/uptime-tracking

user-agent: github.com/lehuygiang28/uptime-tracking
skipDeleteIssues: true

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
